force-app/main/default/objects/Sprint__c/Sprint__c.object-meta.xml
<CustomObject>
    <label>Sprint</label>
    <nameField>
        <displayFormat>Sprint-{0000}</displayFormat>
        <label>Sprint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sprint__c/fields/Release_Date__c.field-meta.xml
<CustomField>
    <fullName>Release_Date__c</fullName>
    <label>Release Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sprint__c/fields/SIT_Date__c.field-meta.xml
<CustomField>
    <fullName>SIT_Date__c</fullName>
    <label>SIT Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sprint__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Track</fullName>
                <default>true</default>
                <label>On Track</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Postponed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sprint__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Sprint__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Stable</fullName>
                <default>true</default>
                <label>Stable</label>
            </value>
            <value>
                <fullName>Beta</fullName>
            </value>
            <value>
                <fullName>Emergency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sprint__c/fields/UAT_Date__c.field-meta.xml
<CustomField>
    <fullName>UAT_Date__c</fullName>
    <label>UAT Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <label>User Story</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Story__c/fields/Patch_Notes__c.field-meta.xml
<CustomField>
    <fullName>Patch_Notes__c</fullName>
    <label>Patch Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/User_Story__c/fields/Sprint__c.field-meta.xml
<CustomField>
    <fullName>Sprint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sprint</label>
    <referenceTo>Sprint__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Story__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Dev Started</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Packaging Org</fullName>
            </value>
            <value>
                <fullName>QA Started</fullName>
            </value>
            <value>
                <fullName>Sandbox</fullName>
            </value>
            <value>
                <fullName>UAT Started</fullName>
            </value>
            <value>
                <fullName>Not Released</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Story__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Feature Request</fullName>
            </value>
            <value>
                <fullName>Bug</fullName>
            </value>
            <value>
                <fullName>Change Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Story__c/fields/Work_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Item__c</fullName>
    <label>Work Item</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Story_Component__c/User_Story_Component__c.object-meta.xml
<CustomObject>
    <label>User Story Component</label>
    <nameField>
        <displayFormat>USC-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Story Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Story_Component__c/fields/Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Api_Name__c</fullName>
    <label>Api Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Story_Component__c/fields/Change_Type__c.field-meta.xml
<CustomField>
    <fullName>Change_Type__c</fullName>
    <label>Change Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Story_Component__c/fields/Metadata_Type__c.field-meta.xml
<CustomField>
    <fullName>Metadata_Type__c</fullName>
    <label>Metadata Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ApexClass</fullName>
            </value>
            <value>
                <fullName>ApexComponent</fullName>
            </value>
            <value>
                <fullName>ApexPage</fullName>
            </value>
            <value>
                <fullName>ApexTrigger</fullName>
            </value>
            <value>
                <fullName>AuraDefinitionBundle</fullName>
            </value>
            <value>
                <fullName>CustomApplication</fullName>
            </value>
            <value>
                <fullName>CustomField</fullName>
            </value>
            <value>
                <fullName>CustomLabel</fullName>
            </value>
            <value>
                <fullName>CustomMetadata</fullName>
            </value>
            <value>
                <fullName>CustomObject</fullName>
            </value>
            <value>
                <fullName>CustomObjectTranslation</fullName>
            </value>
            <value>
                <fullName>CustomPageWebLink</fullName>
            </value>
            <value>
                <fullName>CustomTab</fullName>
            </value>
            <value>
                <fullName>Dashboard</fullName>
            </value>
            <value>
                <fullName>Document</fullName>
            </value>
            <value>
                <fullName>DuplicateRule</fullName>
            </value>
            <value>
                <fullName>EmailTemplate</fullName>
            </value>
            <value>
                <fullName>FieldSet</fullName>
            </value>
            <value>
                <fullName>FlexiPage</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>HomePageComponent</fullName>
            </value>
            <value>
                <fullName>HomePageLayout</fullName>
            </value>
            <value>
                <fullName>Layout</fullName>
            </value>
            <value>
                <fullName>LeadConvertSettings</fullName>
            </value>
            <value>
                <fullName>Letterhead</fullName>
            </value>
            <value>
                <fullName>LightningComponentBundle</fullName>
            </value>
            <value>
                <fullName>LightningWebComponentBundle</fullName>
            </value>
            <value>
                <fullName>ListView</fullName>
            </value>
            <value>
                <fullName>MatchingRule</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Story_Component__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>User Story Components</relationshipLabel>
    <relationshipName>User_Story_Components</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SprinterTestFactory.cls
public with sharing class SprinterTestFactory {
  public static List<SObject> getSprints() {
    List<SObject> sprints = new List<SObject>();
    SObject sprint1 = (Sobject) Type.forName('Sprint__c').newInstance();
    sprint1.put('Title__c', '2017.06-r1');
    sprint1.put('Release_Date__c', Date.newInstance(2017, 6, 8));
    sprint1.put('SIT_Date__c', Date.newInstance(2017, 6, 7));
    sprint1.put('UAT_Date__c', Date.newInstance(2017, 6, 6));
    sprint1.put('Type__c', 'Stable');
    sprint1.put('Status__c', 'On Track');
    sprint1.put(
      'Description__c',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor i'
    );
    sprints.add(sprint1);

    SObject sprint2 = (Sobject) Type.forName('Sprint__c').newInstance();
    sprint2.put('Title__c', '2019.09-r1');
    sprint2.put('Release_Date__c', Date.newInstance(2019, 9, 5));
    sprint2.put('SIT_Date__c', Date.newInstance(2019, 9, 4));
    sprint2.put('UAT_Date__c', Date.newInstance(2019, 9, 4));
    sprint2.put('Type__c', 'Stable');
    sprint2.put('Status__c', 'Completed');
    sprint2.put(
      'Description__c',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor i'
    );
    sprints.add(sprint2);

    SObject sprint3 = (Sobject) Type.forName('Sprint__c').newInstance();
    sprint3.put('Title__c', '2019.09-r4');
    sprint3.put('Release_Date__c', Date.today().addDays(-100));
    sprint3.put('SIT_Date__c', Date.today().addDays(-100));
    sprint3.put('UAT_Date__c', Date.today().addDays(-100));
    sprint3.put('Type__c', 'Beta');
    sprint3.put('Status__c', 'On Track');
    sprint3.put(
      'Description__c',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor i'
    );
    sprints.add(sprint3);

    SObject sprint4 = (Sobject) Type.forName('Sprint__c').newInstance();
    sprint4.put('Title__c', '2018-09-r1');
    sprint4.put('Release_Date__c', Date.today().addDays(-10));
    sprint4.put('SIT_Date__c', Date.today().addDays(-10));
    sprint4.put('UAT_Date__c', Date.today().addDays(-10));
    sprint4.put('Type__c', 'Emergency');
    sprint4.put('Status__c', 'On Track');
    sprint4.put(
      'Description__c',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor i'
    );
    sprints.add(sprint4);

    SObject sprint5 = (Sobject) Type.forName('Sprint__c').newInstance();
    sprint5.put('Title__c', '2019.07-r1');
    sprint5.put('Release_Date__c', Date.today());
    sprint5.put('SIT_Date__c', Date.today());
    sprint5.put('UAT_Date__c', Date.today());
    sprint5.put('Type__c', 'Stable');
    sprint5.put('Status__c', 'On Track');
    sprint5.put(
      'Description__c',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor i'
    );
    sprints.add(sprint5);

    SObject sprint6 = (Sobject) Type.forName('Sprint__c').newInstance();
    sprint6.put('Title__c', '2020.01-r1');
    sprint6.put('Release_Date__c', Date.today().addDays(2));
    sprint6.put('SIT_Date__c', Date.today().addDays(2));
    sprint6.put('UAT_Date__c', Date.today().addDays(2));
    sprint6.put('Type__c', 'Stable');
    sprint6.put('Status__c', 'On Track');
    sprint6.put(
      'Description__c',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor i'
    );
    sprints.add(sprint6);

    insert sprints;
    return sprints;
  }

  public static List<SObject> getUserStories(List<SObject> sprints) {
    List<SObject> userStories = new List<SObject>();
    for (sObject sprint : sprints) {
      //process record here
      SObject ustory1 = (Sobject) Type.forName('User_Story__c').newInstance();
      ustory1.put(
        'Name',
        'Remove "Host list too long. See attached hostlist.json"'
      );
      ustory1.put(
        'Patch_Notes__c',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'
      );
      ustory1.put('Sprint__c', sprint.Id);
      ustory1.put('Status__c', 'Delivered');
      ustory1.put('Work_Item__c', 'W-6523479');
      ustory1.put('Type__c', 'Feature Request');
      userStories.add(ustory1);
    }
    insert userStories;
    return userStories;
  }

  public static List<SObject> getUserStoryComponents(
    List<SObject> userStories
  ) {
    List<SObject> userStoryComponents = new List<SObject>();
    for (sObject userStory : userStories) {
      //process record here
      SObject ustoryComp1 = (Sobject) Type.forName('User_Story_Component__c')
        .newInstance();
      ustoryComp1.put('Api_Name__c', 'TestClass');
      ustoryComp1.put('Change_Type__c', 'New');
      ustoryComp1.put('Metadata_Type__c', 'ApexClass');
      ustoryComp1.put('User_Story__c', userStory.Id);
      userStoryComponents.add(ustoryComp1);

      SObject ustoryComp2 = (Sobject) Type.forName('User_Story_Component__c')
        .newInstance();
      ustoryComp2.put('Api_Name__c', 'RMAHub');
      ustoryComp2.put('Change_Type__c', 'Update');
      ustoryComp2.put('Metadata_Type__c', 'AuraDefinitionBundle');
      ustoryComp2.put('User_Story__c', userStory.Id);
      userStoryComponents.add(ustoryComp2);
    }
    insert userStoryComponents;
    return userStoryComponents;
  }
}