force-app/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <label>User Story</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Story__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Dev Started</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Packaging Org</fullName>
            </value>
            <value>
                <fullName>QA Started</fullName>
            </value>
            <value>
                <fullName>Sandbox</fullName>
            </value>
            <value>
                <fullName>UAT Started</fullName>
            </value>
            <value>
                <fullName>Not Released</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PicklistPathControllerTest.cls
@isTest
public with sharing class PicklistPathControllerTest {
  @IsTest
  static void getPicklistValuesPositive() {
    Test.startTest();
    //below list should have results from status field on user story object
    List<PicklistPathController.PicklistItem> picklistItems = PicklistPathController.getPicklistValues(
      'User_Story__c',
      'Status__c'
    );
    Test.stopTest();
    System.assert(picklistItems != null, 'No picklist values found');
    System.assert(picklistItems.size() > 0, 'No picklist values found');
  }

  @IsTest
  static void getPicklistValuesNegative1() {
    Test.startTest();
    //below list should have 0 results as no test__c field on user story object
    List<PicklistPathController.PicklistItem> picklistItems = PicklistPathController.getPicklistValues(
      'User_Story__c',
      'Test_Test__c'
    );
    Test.stopTest();
    System.assert(picklistItems == null, 'Incorrect data found');
  }

  @IsTest
  static void getPicklistValuesNegative2() {
    Test.startTest();
    List<PicklistPathController.PicklistItem> picklistItems = PicklistPathController.getPicklistValues(
      'Test_Test__c',
      'Test_Test__c'
    );
    Test.stopTest();
    System.assert(picklistItems == null, 'Incorrect data found');
  }
}